name: Drizzle Migrate Deploy
on:
  push:
    paths:
      - drizzle/** # drizzle/配下の変更時のみ実行
    branches:
      - main

jobs:
  Drizzle-Migrate-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Apply all pending migrations to the database
        run: bunx drizzle-kit migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
